futbin_lite/cards/urls.py
from django.urls import path
from . import views

app_name = 'cards'

urlpatterns = [
    path("players/", views.player_list, name="player_list"),
    path('players/<int:pk>/', views.player_detail, name="player_detail")
]

futbin_lite/futbin_lite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cards.urls'))
]

futbin_lite/cards/models.py
from django.db import models


# Create your models here.

class Player(models.Model):
    name = models.CharField(max_length=100)
    nation = models.CharField(max_length=50)
    club = models.CharField(max_length=50)
    league = models.CharField(max_length=50)
    position = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.name} ({self.position})"


class PlayerCard(models.Model):
    name = models.CharField(max_length=100)
    rating = models.IntegerField()
    position = models.CharField(max_length=10)
    club = models.CharField(max_length=100)
    nation = models.CharField(max_length=100)
    pace = models.IntegerField()
    shooting = models.IntegerField()
    passing = models.IntegerField()
    dribbling = models.IntegerField()
    defending = models.IntegerField()
    physical = models.IntegerField()

    def __str__(self):
        return f'{self.name} ({self.rating})'

futbin_lite/cards/views.py
from django.shortcuts import render, get_object_or_404
from .models import PlayerCard


# Create your views here.
def player_list(request):
    players = PlayerCard.objects.all()
    return render(request, 'cards/player_list.html', {'players': players})


def player_detail(request, pk):
    player = get_object_or_404(PlayerCard, pk=pk)
    return render(request, 'cards/player_detail.html', {'player': player})

futbin_lite/cards/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Futbin Lite{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'cards/style.css' %}">
</head>
<body>
<header>
    <h1>⚽ Futbin Lite</h1>
    <nav>
        <a href="{% url 'cards:player_list' %}">Players</a>
    </nav>
</header>
<main>
    {% block content %}{% endblock %}
</main>

</body>
</html>

futbin_lite/cards/templates/cards/player_detail.html
{% extends "base.html" %}

{% block title %}{{ player.name }}{% endblock %}

{% block content %}
<h2>{{ player.name }}</h2>
<p>Rating: {{ player.rating }}</p>
<p>Position: {{ player.position }}</p>
<p>Club: {{ player.club }}</p>
<p>Nation: {{ player.nation }}</p>
<a href="{% url 'cards:player_list' %}">Back to list</a>
{% endblock %}

futbin_lite/cards/templates/cards/player_list.html
{% extends "base.html" %}

{% block title %}Players{% endblock %}

{% block content %}
<h2>List of Players</h2>
<ul>
    {% for player in players %}
    <li>
        <a href="{% url 'cards:player_detail' player.pk %}">
            {{ player.name }}{{ player.rating }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}